version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme2
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - TZ=America/Santiago
    volumes:
      - n8n_data:/home/node/.n8n
    user: "${PUID}:${PGID}"

volumes:
  n8n_data: