services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}  # Puedes cambiarla luego
    volumes:
      - pihole_config:/etc/pihole
      - dnsmasq_config:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_WEBPORT}:80"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

volumes:
  pihole_config:
  dnsmasq_config: