version: "3.8"

services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - jackett_config:/config
      - /mnt/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    user: "${PUID}:${PGID}"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - sonarr_config:/config
      - /mnt/media:/media
      - /mnt/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    user: "${PUID}:${PGID}"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - radarr_config:/config
      - /mnt/media:/media
      - /mnt/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    user: "${PUID}:${PGID}"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - transmission_config:/config
      - /mnt/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    user: "${PUID}:${PGID}"

volumes:
  jackett_config:
  radarr_config:
  sonarr_config:
  transmission_config: