version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3001:3000"
    volumes:
      - /opt/docker-data/homepage:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Santiago}
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true