services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/media:/media:ro
    restart: unless-stopped
    user: "${PUID}:${PGID}"

volumes:
  jellyfin_config:
  jellyfin_cache: